import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import { hasLocale, NextIntlClientProvider } from 'next-intl'

import '../globals.css'

import { routing } from '@/i18n/routing'
import { notFound } from 'next/navigation'
import Provider from '@/components/provider'

const manrope = Manrope({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params.catch(() => ({ locale: 'en' }))

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body key={locale} className={`${manrope.className} antialiased dark:bg-foreground dark:text-background`}>
        <NextIntlClientProvider locale={locale}>
          <Provider>{children}</Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
